# Generated by Django 2.1.7 on 2019-03-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedb', '0002_auto_20190313_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6),
        ),
        migrations.AlterField(
            model_name='award',
            name='kind',
            field=models.CharField(choices=[('Movie', 'Movie'), ('Actor', 'Actor')], max_length=5),
        ),
        migrations.AlterField(
            model_name='commentactor',
            name='content',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='commentaward',
            name='content',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='commentmovie',
            name='content',
            field=models.TextField(max_length=256),
        ),
    ]
